#!/bin/sh

ADDONNAME=sonos2
RCDDIR=/usr/local/etc/config/rc.d
ADDONDIR=/usr/local/etc/config/addons/${ADDONNAME}
WWWDIR=/usr/local/etc/config/addons/www/${ADDONNAME}

AUTOSTART_SCRIPT=${ADDONNAME}
START_SCRIPT=${ADDONNAME}.tcl
STOP_SCRIPT=stop.tcl
CONFIG_URL=/addons/${ADDONNAME}/settings/settings.cgi

# check for unsupported platforms
if grep -qim1 busmatic /www/api/methods/ccu/downloadFirmware.tcl; then
  exit 13
fi

# change to addon directory
cd ${ADDONDIR}

case "$1" in
  ""|start)
    tclsh $START_SCRIPT &
    ;;

  info)
    VER=$(cat ${ADDONDIR}/VERSION)
    echo "Version: ${VER}"
    echo "Info: <b>Sonos Player CCU Addon</b><br>"
    echo "Info: Copyright (c) 2014-2021 fiveyears, Jens Maus<br>"
    echo "Info: <a href='https://github.com/homematic-community/hm-sonos'>https://github.com/homematic-community/hm-sonos</a>"
    echo "Name: Sonos Player"
    echo "Operations: uninstall restart"
    echo "Config-Url: $CONFIG_URL"
    echo "Update: /addons/${ADDONNAME}/update-check.cgi"
    ;;

  restart)
    tclsh $STOP_SCRIPT
    tclsh $START_SCRIPT &
    ;;

  stop)
    tclsh $STOP_SCRIPT
    ;;

  uninstall)
    tclsh $STOP_SCRIPT
    cd ${RCDDIR}
  
    ${WWWDIR}/bin/update_addon ${ADDONNAME}
    rm -rf ${ADDONDIR}
    rm -rf ${WWWDIR}
    rm -rf ${AUTOSTART_SCRIPT}
    ;;

  *)
    echo "usage:"
    echo "  ${ADDONNAME} [info|start|stop|restart|uninstall]"
    ;;
esac
