#!/bin/sh
ADDONNAME=sonos2
CONFIGDIR=/usr/local/etc/config
AUTOSTART_DIR=$CONFIGDIR/rc.d
ADDON_DIR=$CONFIGDIR/addons/$ADDONNAME
WWW_DIR=$CONFIGDIR/addons/www/$ADDONNAME

AUTOSTART_SCRIPT=$ADDONNAME
START_SCRIPT=$ADDONNAME.tcl
STOP_SCRIPT=stop.tcl
CONFIG_URL=/addons/$ADDONNAME/settings/settings.cgi

cd $ADDON_DIR

case "$1" in
""|start)
	tclsh $START_SCRIPT &
	;;
info)
	echo "Version: 2.1"
	echo "Info: <b>Sonosscripte f&uuml;r die CCU2</b>"
    echo "Info: <br>Aufruf: <a href="/addons/$ADDONNAME/sonos2.cgi" target="_blank">http://CCU/addons/$ADDONNAME/sonos2.cgi</a>"
    echo "Info: <br>Readme: <a href="http://ivodoehler.com" target="_blank">Ivo D&ouml;hler</a>"
      
	echo "Name: Sonosscripte f&uuml;r die CCU2"
	echo "Operations: uninstall"
	echo "Config-Url: $CONFIG_URL"
	;;
restart)
	tclsh $STOP_SCRIPT
	tclsh $START_SCRIPT &
	;;
stop)
	tclsh $STOP_SCRIPT
	;;
uninstall)
	tclsh $STOP_SCRIPT
	cd $AUTOSTART_DIR

	rm -rf $ADDON_DIR
	rm -rf $WWW_DIR
	rm -rf $AUTOSTART_SCRIPT
	;;
*)
	echo "usage:"
	echo "  $ADDONNAME [info|start|stop|restart|uninstall]"
	;;
esac
