#!/bin/sh

ADDONNAME=sonos2
RCDDIR=/usr/local/etc/config/rc.d
ADDONDIR=/usr/local/etc/config/addons/${ADDONNAME}
WWWDIR=/usr/local/etc/config/addons/www/${ADDONNAME}

# check for unsupported platforms
if grep -qim1 busmatic /www/api/methods/ccu/downloadFirmware.tcl; then
  exit 13
fi

if [ "$1" == "" ]; then
  echo "CCU1"
  lcdtool "Installing Sonos...   "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" == "CCU2" ]; then
  echo "CCU2"
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  mount /usr/local
fi

# copy rc.d script
mkdir -p ${RCDDIR}
chmod 755 ${RCDDIR}
cp rc.d/${ADDONNAME} ${RCDDIR}/
chmod +x ${RCDDIR}/${ADDONNAME}

# copy web configuration pages
mkdir -p ${WWWDIR}
chmod 755 ${WWWDIR}
cp -R www/* ${WWWDIR}/

# copy addon directory
mkdir -p ${ADDONDIR}
chmod 755 ${ADDONDIR}
cp -R ${ADDONNAME}/* ${ADDONDIR}

# copy CCU specific binaries to the bin directory
mkdir -p ${WWWDIR}/bin
if [ "$1" == "" ]; then
  cp -a ccu1/* ${WWWDIR}/bin/
elif [ "$1" == "CCU2" ]; then
  cp -a ccu2/* ${WWWDIR}/bin/
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  if [ "$(uname -m)" == "i686" ] || [ "$(uname -m)" == "x86_64" ]; then
    cp -a ccu3x86/* ${WWWDIR}/bin/
  else
    cp -a ccu3/* ${WWWDIR}/bin/
  fi
fi

# add menu entry
touch /usr/local/etc/config/hm_addons.cfg
${WWWDIR}/bin/update_addon sonos2 ${ADDONDIR}/sonos2_addon.cfg

# sync filesystem to make sure all changes are written to disk
sync

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
